/**
 * 组件配置接口
 */
export interface ComponentConfig {
    icon: string;
    label: string;
    widgetName: string;
    title: string;
    subTitle?: string;
    renderKey: string;
    visibility: string[];
    showLabel: boolean;
    active?: string;
    children?: Array<{
        name: string;
        children: any[];
    }>;
    card: {
        titleFontSize: number;
        titleFontWeight: boolean;
        titleFontColor: string;
        titleLeft: string;
        titleBgColor: string;
        cardIcon: string;
        cardIconColor: string;
        linkType: string;
        type: string;
        moduleId: string;
        urlAddress: string;
        linkTarget: string;
        appLinkType: string;
        appType: string;
        appModuleId: string;
        appUrlAddress: string;
        cardStyle: string;
        backgroundType: string;
        backgroudImage: string;
    };
    option: {
        styleType?: number;
        appStyleType?: number;
        openGrouping?: boolean;
        groupingType?: string;
        defaultValue?: any[];
        appDefaultValue?: any[];
        rowNumber?: number;
        showBorder?: boolean;
        appRowNumber?: number;
        appShowBorder?: boolean;
        labelFontSize?: number;
        labelFontWeight?: boolean;
        labelFontColor?: string;
        briefingFields?: any[] | string;
        backgroundType?: string;
        backgroundImage?: string;
        stepsType?: string;
        stageKey?: any;
        editDirectly?: boolean;
        dataTableConfig?: {
            showAddData: boolean;
            isSearchSingerData: boolean;
            dataSourceFormId: string;
            chooseDataConfig: {
                fieldKey: any;
                checked: any;
                sort: any;
                displayFields: any[];
                filter: {
                    rel: string;
                    conds: any[];
                };
            };
        };
        dataEntruFormId?: string;
        fillFields?: any[];
        autoPlay?: boolean;
        interval?: number;
        pictureField?: string;
        pictureType?: string;
        fillType?: string;
        carouselPictures?: any[];
        timeLineType?: string;
        dataShows?: {
            title: string;
            time: string;
            description: string;
        };
        reverse?: boolean;
        iframeUrl?: string;
    };
    w: number;
    h: number;
    minW: number;
    minH: number;
    maxW: number;
    maxH: number;
}

// 基础控件
export const basicComponents: ComponentConfig[] = [
    {
        icon: 'Postcard',
        label: '简报卡片',
        widgetName: 'briefingCard',
        title: '简报卡片',
        subTitle: '副标题',
        renderKey: '',
        visibility: ['pc', 'app'],
        showLabel: true,
        card: {
            titleFontSize: 14,
            titleFontWeight: false,
            titleFontColor: '#303133',
            titleLeft: 'left',
            titleBgColor: '',
            cardIcon: 'icon-ym icon-ym-generator-function',
            cardIconColor: '#606266',
            linkType: '',
            type: '',
            moduleId: '',
            urlAddress: '',
            linkTarget: '_blank',
            appLinkType: '',
            appType: '',
            appModuleId: '',
            appUrlAddress: '',
            cardStyle: 'card',
            backgroundType: 'color',
            backgroudImage: '',
        },
        option: {
            styleType: 1,
            appStyleType: 1,
            openGrouping: false,
            groupingType: 'Tab',
            defaultValue: [],
            appDefaultValue: [],
            rowNumber: 5,
            showBorder: false,
            appRowNumber: 4,
            appShowBorder: false,
            labelFontSize: 14,
            labelFontWeight: false,
            labelFontColor: '#606266',
            briefingFields: [],
            backgroundType: 'color',
            backgroundImage: '',
        },
        w: 12,
        h: 4,
        minW: 2,
        minH: 3,
        maxW: 12,
        maxH: 12,
    },
    {
        icon: 'Operation',
        label: '阶段条',
        widgetName: 'steps',
        title: '阶段条',
        renderKey: '',
        visibility: ['pc', 'app'],
        showLabel: true,
        card: {
            titleFontSize: 14,
            titleFontWeight: false,
            titleFontColor: '#303133',
            titleLeft: 'left',
            titleBgColor: '',
            cardIcon: 'icon-ym icon-ym-generator-function',
            cardIconColor: '#606266',
            linkType: '',
            type: '',
            moduleId: '',
            urlAddress: '',
            linkTarget: '_blank',
            appLinkType: '',
            appType: '',
            appModuleId: '',
            appUrlAddress: '',
            cardStyle: 'card',
            backgroundType: 'color',
            backgroudImage: '',
        },
        option: {
            stepsType: 'simple',
            stageKey: null,
            editDirectly: false,
            appStyleType: 1,
            openGrouping: false,
            groupingType: 'Tab',
            defaultValue: [],
            appDefaultValue: [],
            rowNumber: 5,
            showBorder: false,
            appRowNumber: 4,
            appShowBorder: false,
            labelFontSize: 14,
            labelFontWeight: false,
            labelFontColor: '#606266',
        },
        w: 12,
        h: 6,
        minW: 2,
        minH: 6,
        maxW: 12,
        maxH: 22,
    },
    {
        icon: 'CopyDocument',
        label: '多标签页',
        widgetName: 'tab',
        title: '多标签页',
        renderKey: '',
        visibility: ['pc', 'app'],
        active: 'Tab 1',
        showLabel: true,
        children: [
            {
                name: 'Tab 1',
                children: [],
            },
            {
                name: 'Tab 2',
                children: [],
            },
        ],
        card: {
            titleFontSize: 14,
            titleFontWeight: false,
            titleFontColor: '#303133',
            titleLeft: 'left',
            titleBgColor: '',
            cardIcon: 'icon-ym icon-ym-generator-function',
            cardIconColor: '#606266',
            linkType: '',
            type: '',
            moduleId: '',
            urlAddress: '',
            linkTarget: '_blank',
            appLinkType: '',
            appType: '',
            appModuleId: '',
            appUrlAddress: '',
            cardStyle: 'card',
            backgroundType: 'color',
            backgroudImage: '',
        },
        option: {
            stepsType: 'simple',
            stageKey: null,
            editDirectly: false,
            appStyleType: 1,
            openGrouping: false,
            groupingType: 'Tab',
            defaultValue: [],
            appDefaultValue: [],
            rowNumber: 5,
            showBorder: false,
            appRowNumber: 4,
            appShowBorder: false,
            labelFontSize: 14,
            labelFontWeight: false,
            labelFontColor: '#606266',
        },
        w: 12,
        h: 8,
        minW: 12,
        minH: 6,
        maxW: 12,
        maxH: 20,
    },
    {
        icon: 'Crop',
        label: '表单字段',
        widgetName: 'formField',
        title: '表单字段',
        renderKey: '',
        visibility: ['pc', 'app'],
        showLabel: true,
        card: {
            titleFontSize: 14,
            titleFontWeight: false,
            titleFontColor: '#303133',
            titleLeft: 'left',
            titleBgColor: '',
            cardIcon: 'icon-ym icon-ym-generator-function',
            cardIconColor: '#606266',
            linkType: '',
            type: '',
            moduleId: '',
            urlAddress: '',
            linkTarget: '_blank',
            appLinkType: '',
            appType: '',
            appModuleId: '',
            appUrlAddress: '',
            cardStyle: 'card',
            backgroundType: 'color',
            backgroudImage: '',
        },
        option: {
            stepsType: 'simple',
            stageKey: null,
            editDirectly: false,
            appStyleType: 1,
            openGrouping: false,
            groupingType: 'Tab',
            defaultValue: [],
            appDefaultValue: [],
            rowNumber: 5,
            showBorder: false,
            appRowNumber: 4,
            appShowBorder: false,
            labelFontSize: 14,
            labelFontWeight: false,
            labelFontColor: '#606266',
        },
        w: 12,
        h: 6,
        minW: 2,
        minH: 6,
        maxW: 12,
        maxH: 22,
    },
    {
        icon: 'Grid',
        label: '数据表格',
        widgetName: 'dataTable',
        title: '数据表格',
        renderKey: '',
        visibility: ['pc', 'app'],
        showLabel: true,
        card: {
            titleFontSize: 14,
            titleFontWeight: false,
            titleFontColor: '#303133',
            titleLeft: 'left',
            titleBgColor: '',
            cardIcon: 'icon-ym icon-ym-generator-function',
            cardIconColor: '#606266',
            linkType: '',
            type: '',
            moduleId: '',
            urlAddress: '',
            linkTarget: '_blank',
            appLinkType: '',
            appType: '',
            appModuleId: '',
            appUrlAddress: '',
            cardStyle: 'card',
            backgroundType: 'color',
            backgroudImage: '',
        },
        option: {
            styleType: 1,
            appStyleType: 1,
            openGrouping: false,
            groupingType: 'Tab',
            defaultValue: [],
            appDefaultValue: [],
            rowNumber: 5,
            showBorder: false,
            appRowNumber: 4,
            appShowBorder: false,
            labelFontSize: 14,
            labelFontWeight: false,
            labelFontColor: '#606266',
            dataTableConfig: {
                showAddData: false,
                isSearchSingerData: false,
                dataSourceFormId: '',
                chooseDataConfig: {
                    fieldKey: null,
                    checked: null,
                    sort: null,
                    displayFields: [],
                    filter: {
                        rel: 'or',
                        conds: [],
                    },
                },
            },
        },
        w: 12,
        h: 5,
        minW: 2,
        minH: 5,
        maxW: 12,
        maxH: 12,
    },
    {
        icon: 'Coin',
        label: '数据填报',
        widgetName: 'dataEntry',
        title: '数据填报',
        renderKey: '',
        visibility: ['pc', 'app'],
        showLabel: true,
        card: {
            titleFontSize: 14,
            titleFontWeight: false,
            titleFontColor: '#303133',
            titleLeft: 'left',
            titleBgColor: '',
            cardIcon: 'icon-ym icon-ym-generator-function',
            cardIconColor: '#606266',
            linkType: '',
            type: '',
            moduleId: '',
            urlAddress: '',
            linkTarget: '_blank',
            appLinkType: '',
            appType: '',
            appModuleId: '',
            appUrlAddress: '',
            cardStyle: 'card',
            backgroundType: 'color',
            backgroudImage: '',
        },
        option: {
            styleType: 1,
            appStyleType: 1,
            openGrouping: false,
            groupingType: 'Tab',
            defaultValue: [],
            appDefaultValue: [],
            rowNumber: 5,
            showBorder: false,
            appRowNumber: 4,
            appShowBorder: false,
            labelFontSize: 14,
            labelFontWeight: false,
            labelFontColor: '#606266',
            dataEntruFormId: '',
            fillFields: [],
        },
        w: 12,
        h: 4,
        minW: 2,
        minH: 3,
        maxW: 12,
        maxH: 12,
    },
    {
        icon: 'Help',
        label: '数据动态',
        widgetName: 'dataDynamics',
        title: '数据动态',
        renderKey: '',
        visibility: ['pc', 'app'],
        showLabel: true,
        card: {
            titleFontSize: 14,
            titleFontWeight: false,
            titleFontColor: '#303133',
            titleLeft: 'left',
            titleBgColor: '',
            cardIcon: 'icon-ym icon-ym-generator-function',
            cardIconColor: '#606266',
            linkType: '',
            type: '',
            moduleId: '',
            urlAddress: '',
            linkTarget: '_blank',
            appLinkType: '',
            appType: '',
            appModuleId: '',
            appUrlAddress: '',
            cardStyle: 'card',
            backgroundType: 'color',
            backgroudImage: '',
        },
        option: {
            styleType: 1,
            appStyleType: 1,
            openGrouping: false,
            groupingType: 'Tab',
            defaultValue: [],
            appDefaultValue: [],
            rowNumber: 5,
            showBorder: false,
            appRowNumber: 4,
            appShowBorder: false,
            labelFontSize: 14,
            labelFontWeight: false,
            labelFontColor: '#606266',
            autoPlay: false,
            interval: 3000,
            pictureField: '',
            pictureType: 'data',
            fillType: 'fill',
            briefingFields: '',
            backgroundType: 'color',
            backgroundImage: '',
            carouselPictures: [],
        },
        w: 12,
        h: 4,
        minW: 2,
        minH: 3,
        maxW: 12,
        maxH: 12,
    },
    {
        icon: 'Calendar',
        label: '时间线',
        widgetName: 'timeLine',
        title: '时间线',
        renderKey: '',
        visibility: ['pc', 'app'],
        showLabel: true,
        card: {
            titleFontSize: 14,
            titleFontWeight: false,
            titleFontColor: '#303133',
            titleLeft: 'left',
            titleBgColor: '',
            cardIcon: 'icon-ym icon-ym-generator-function',
            cardIconColor: '#606266',
            linkType: '',
            type: '',
            moduleId: '',
            urlAddress: '',
            linkTarget: '_blank',
            appLinkType: '',
            appType: '',
            appModuleId: '',
            appUrlAddress: '',
            cardStyle: 'card',
            backgroundType: 'color',
            backgroudImage: '',
        },
        option: {
            timeLineType: 'card',
            dataShows: {
                title: 'title',
                time: 'time',
                description: 'description',
            },
            reverse: false,
            styleType: 1,
            appStyleType: 1,
            openGrouping: false,
            groupingType: 'Tab',
            defaultValue: [],
            appDefaultValue: [],
            rowNumber: 5,
            showBorder: false,
            appRowNumber: 4,
            appShowBorder: false,
            labelFontSize: 14,
            labelFontWeight: false,
            labelFontColor: '#606266',
        },
        w: 12,
        h: 6,
        minW: 2,
        minH: 6,
        maxW: 12,
        maxH: 22,
    },
    {
        icon: 'Picture',
        label: '轮播图',
        widgetName: 'carousel',
        title: '轮播图',
        renderKey: '',
        visibility: ['pc', 'app'],
        showLabel: true,
        card: {
            titleFontSize: 14,
            titleFontWeight: false,
            titleFontColor: '#303133',
            titleLeft: 'left',
            titleBgColor: '',
            cardIcon: 'icon-ym icon-ym-generator-function',
            cardIconColor: '#606266',
            linkType: '',
            type: '',
            moduleId: '',
            urlAddress: '',
            linkTarget: '_blank',
            appLinkType: '',
            appType: '',
            appModuleId: '',
            appUrlAddress: '',
            cardStyle: 'card',
            backgroundType: 'color',
            backgroudImage: '',
        },
        option: {
            styleType: 1,
            appStyleType: 1,
            openGrouping: false,
            groupingType: 'Tab',
            defaultValue: [],
            appDefaultValue: [],
            rowNumber: 5,
            showBorder: false,
            appRowNumber: 4,
            appShowBorder: false,
            labelFontSize: 14,
            labelFontWeight: false,
            labelFontColor: '#606266',
            autoPlay: false,
            interval: 3000,
            pictureField: '',
            pictureType: 'data',
            fillType: 'fill',
            briefingFields: '',
            backgroundType: 'color',
            backgroundImage: '',
            carouselPictures: [],
        },
        w: 12,
        h: 4,
        minW: 2,
        minH: 3,
        maxW: 12,
        maxH: 12,
    },
    {
        icon: 'PriceTag',
        label: '富文本',
        widgetName: 'richText',
        title: '富文本',
        renderKey: '',
        visibility: ['pc', 'app'],
        showLabel: true,
        card: {
            titleFontSize: 14,
            titleFontWeight: false,
            titleFontColor: '#303133',
            titleLeft: 'left',
            titleBgColor: '',
            cardIcon: 'icon-ym icon-ym-generator-function',
            cardIconColor: '#606266',
            linkType: '',
            type: '',
            moduleId: '',
            urlAddress: '',
            linkTarget: '_blank',
            appLinkType: '',
            appType: '',
            appModuleId: '',
            appUrlAddress: '',
            cardStyle: 'card',
            backgroundType: 'color',
            backgroudImage: '',
        },
        option: {
            styleType: 1,
            appStyleType: 1,
            openGrouping: false,
            groupingType: 'Tab',
            defaultValue: [],
            appDefaultValue: [],
            rowNumber: 5,
            showBorder: false,
            appRowNumber: 4,
            appShowBorder: false,
            labelFontSize: 14,
            labelFontWeight: false,
            labelFontColor: '#606266',
        },
        w: 12,
        h: 6,
        minW: 2,
        minH: 6,
        maxW: 12,
        maxH: 22,
    },
    {
        icon: 'DataBoard',
        label: '嵌入页面',
        widgetName: 'iframe',
        title: '嵌入页面',
        renderKey: '',
        visibility: ['pc', 'app'],
        showLabel: true,
        card: {
            titleFontSize: 14,
            titleFontWeight: false,
            titleFontColor: '#303133',
            titleLeft: 'left',
            titleBgColor: '',
            cardIcon: 'icon-ym icon-ym-generator-function',
            cardIconColor: '#606266',
            linkType: '',
            type: '',
            moduleId: '',
            urlAddress: '',
            linkTarget: '_blank',
            appLinkType: '',
            appType: '',
            appModuleId: '',
            appUrlAddress: '',
            cardStyle: 'card',
            backgroundType: 'color',
            backgroudImage: '',
        },
        option: {
            styleType: 1,
            appStyleType: 1,
            openGrouping: false,
            groupingType: 'Tab',
            defaultValue: [],
            appDefaultValue: [],
            rowNumber: 5,
            showBorder: false,
            appRowNumber: 4,
            appShowBorder: false,
            labelFontSize: 14,
            labelFontWeight: false,
            labelFontColor: '#606266',
            iframeUrl: '',
            backgroundType: 'color',
            backgroundImage: '',
        },
        w: 12,
        h: 4,
        minW: 2,
        minH: 3,
        maxW: 12,
        maxH: 12,
    },
];
